### ISSUE TITLE
Issue with Serverless offline plugin

### ISSUE THREAD

**Issue by anil-grexit** [erm/mangum#53]
```python
from mangum import Mangum
from fastapi import FastAPI


app = FastAPI()


@app.post("/items/")
def create_item(item_id: int):
    return {"id": item_id}


@app.get("/items/")
def list_items():
    items = [{"id": i} for i in range(10)]
    return items


@app.get("/")
def read_root():
    return {"Hello": "World!"}


handler = Mangum(app)
```

I'm using the above code when specified in `main.py` and it's configured with a catch-all route in `serverless.yml`. I want to test it locally using the `serverless-offline` plugin but when I run the offline plugin using `sls offline`, I don't get any response in the browser for any routes. It just says, `localhost didn’t send any data`.

What could I be doing wrong? The offline plugin is listening on port `3000` by default.

**Comment by erm** [comment]
@anil-grexit can you post your `serverless.yml`?

I tried to re-create your issue using the example here: https://github.com/chgangaraju/fastapi-mangum-example (**NOTE**: I changed the Mangum and FastAPI requirements to be the latest versions and Python 3.7), however I did not have any issues using the `serverless-offline` plugin with the following `serverless.yml`:

```
service: fastapi-mangum-example

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'test'}
  environment:
    REGION: ${self:provider.region}
    LOG_LEVEL: ${opt:loglevel, 'INFO'}

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
    - .direnv/**


functions:
  app:
    handler: app.main.handler
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-offline
```
